"""Strata security-fix discovery primitives."""

from .contracts import (
    CWE_CATALOG_VERSION,
    FINDING_SCHEMA_VERSION,
    TRIAGE_DECISION_SCHEMA_VERSION,
    ContractErrorV1,
    ContractValidationError,
    ErrorKind,
    EvidenceAnchorV1,
    EvidenceClaim,
    EvidenceRevision,
    FindingV1,
    FindingVerdict,
    FixCompleteness,
    InputProfile,
    L0Class,
    ParserStatus,
    ProviderSettingsV1,
    RunProvenanceV1,
    SeverityLevel,
    SeveritySource,
    SeverityV1,
    TokenUsageV1,
    TriageChunkResultV1,
    TriageDecisionV1,
    TriageVerdict,
    canonical_hash,
    canonical_json,
    sha256_bytes,
    sha256_text,
    validate_finding,
    validate_triage_decision,
)

__all__ = [
    "CWE_CATALOG_VERSION",
    "FINDING_SCHEMA_VERSION",
    "TRIAGE_DECISION_SCHEMA_VERSION",
    "ContractErrorV1",
    "ContractValidationError",
    "ErrorKind",
    "EvidenceAnchorV1",
    "EvidenceClaim",
    "EvidenceRevision",
    "FindingV1",
    "FindingVerdict",
    "FixCompleteness",
    "InputProfile",
    "L0Class",
    "ParserStatus",
    "ProviderSettingsV1",
    "RunProvenanceV1",
    "SeverityLevel",
    "SeveritySource",
    "SeverityV1",
    "TokenUsageV1",
    "TriageChunkResultV1",
    "TriageDecisionV1",
    "TriageVerdict",
    "canonical_hash",
    "canonical_json",
    "sha256_bytes",
    "sha256_text",
    "validate_finding",
    "validate_triage_decision",
]

__version__ = "0.1.0"
